baseURL = "https://chaoya.top/"
languageCode = "zh-cn"
title = "Chaoya Li's Blog"
theme = "chaoya-blog"
googleAnalytics = "UA-27568125-1"
hasCJKLanguage = true
enableGitInfo = true

[markup.goldmark.renderer]
unsafe= true

[params]
  copyright = "Chaoya Li. All right reserved."
  since = 2016
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[permalinks]
  posts = "/:year/:month/:filename/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 100

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 200

[[menu.social]]
  name = "Github"
  url = "https://github.com/harry75369"
  pre = "<i class='fab fa-lg fa-github'></i>"

[[menu.social]]
  name = "Zhihu"
  url = "https://www.zhihu.com/people/li-harry"
  pre = "<i class='fab fa-lg fa-zhihu'></i>"

[[menu.social]]
  name = "Linkedin"
  url = "https://www.linkedin.com/in/chaoya-li-harry"
  pre = "<i class='fab fa-lg fa-linkedin'></i>"

